import Head from "next/head";
import { Inter } from "@next/font/google";
import Navbar from "../Components/navbar/navbar";
import Aside from "../Components/aside/aside";
import Description from "../Components/description/description";
import { useEffect, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
	const [orders, setOrders] = useState(0);
	const [windowWidth, setWindowWidth] = useState(0);

	useEffect(() => {
		function handleWindowResize() {
			setWindowWidth(window.innerWidth);
		}
		handleWindowResize();

		window.addEventListener("resize", handleWindowResize);

		return () => {
			window.removeEventListener("resize", handleWindowResize);
		};
	}, []);

	function changeOrders(number) {
		setOrders(number);
	}
	function deleteOrders() {
		setOrders(0);
	}

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<header className="w-full xl:w-[1350px] xl:min-w-[1350px]">
				<Navbar orders={orders} deleteOrders={deleteOrders} />
			</header>
			<main
				className="md:pt-28 md:px-16 md:flex md:gap-36 w-full
			 xl:w-[1350px] xl:min-w-[1350px]"
			>
				<Aside windowWidth={windowWidth} />
				<Description changeOrders={changeOrders} />
			</main>
		</>
	);
}
